webapp/tasks/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import SelectField, StringField, SubmitField, TextAreaField
from wtforms.fields.html5 import DateField, TimeField
from wtforms.validators import DataRequired
from datetime import datetime
from pytz import timezone


tz = timezone('Europe/Vienna')

class CommentForm(FlaskForm):
    content = TextAreaField('Content')
    submit = SubmitField('Comment')

class UploadForm(FlaskForm):
    upload = FileField('Upload', validators=[DataRequired(), FileAllowed(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'doc', 'docx', 'pptx', 'xlsx', 'gap'])])
    submit = SubmitField('Upload File')

class AddTaskForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    deadline_date = DateField('Deadline', validators=[DataRequired()], default=datetime.now(tz))
    deadline_time = TimeField('Deadline', validators=[DataRequired()], default=datetime.now(tz))
    subject = SelectField('Subject', choices=[], coerce=int, validators=[DataRequired()])
    submit = SubmitField('Add')

webapp/main/routes.py
from webapp import db
from webapp.models import Subject, User
from flask import abort, Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required


main = Blueprint('main', __name__)

@main.route('/config', methods=['GET', 'POST'])
@login_required
def config():
    if current_user.status == 'user':
        abort(403)
    users = User.query.all()
    editors = User.query.filter_by(status='editor').all()
    god_mode = User.query.filter_by(status='god_mode').all()
    return render_template('config.html', title='Config', editors=editors+god_mode, users=users)

@main.route('/subject', methods=['GET', 'POST'])
@login_required
def add_subject():
    subjects = Subject.query.all()
    if request.method == 'POST' and request.form['name'] != '':
        db.session.add(Subject(name=request.form['name']))
        db.session.commit()
        return redirect(url_for('main.add_subject'))
    return render_template('add_subject.html', title='Subject', subjects=subjects)

@main.route('/subject/<int:subject_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_subject(subject_id):
    subject = Subject.query.get_or_404(subject_id)
    if current_user.status == 'user':
        abort(403)
    db.session.delete(subject)
    db.session.commit()
    return redirect(url_for('main.add_subject'))

@main.route('/makeditor/<string:username>')
@login_required
def make_editor(username):
    if current_user.status != 'god_mode':
        abort(403)
    user = User.query.filter_by(username=username).first()
    if not user:
        abort(404)
    user.status = 'editor'
    db.session.commit()
    return redirect(url_for('users.profile', username=user.username))

webapp/tasks/routes.py
from webapp import db
from webapp.main.utils import delete_file
from webapp.models import Comment, Material, Subject, Task
from webapp.tasks.forms import AddTaskForm, CommentForm, UploadForm
from webapp.tasks.utils import add_file
from flask import abort, Blueprint, current_app, flash, redirect, render_template, request, send_from_directory, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from datetime import datetime
import os


tasks = Blueprint('tasks', __name__)


@tasks.route('/')
@tasks.route('/home')
@tasks.route('/schedule')
@login_required
def schedule():
    return render_template('schedule.html', title='Schedule', schedule=Task.query.all())


@tasks.route('/task/<int:task_id>')
@login_required
def task(task_id):
    task = Task.query.get(task_id)
    subject = Subject.query.get(task.subject_id)
    return render_template('task.html', title=task.name, task=task, subject=subject)


@tasks.route('/comment/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def comment(comment_id):
    form = CommentForm()
    comment = Comment.query.get(comment_id)
    task = Task.query.get(comment.task_id)

    if form.validate_on_submit():
        comment.comment = form.content.data
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('tasks.task', task_id=task.id))

    if request.method == 'GET':
        form.content.data = comment.comment

    return render_template('comment.html', title=task.name, comment=comment, task=task, form=form)


@tasks.route('/task/<int:task_id>/comment', defaults={'anonymous': None}, methods=['GET', 'POST'])
@tasks.route('/task/<int:task_id>/comment/<string:anonymous>', methods=['GET', 'POST'])
@login_required
def add_comment_content(task_id, anonymous):
    form = CommentForm()

    task = Task.query.get_or_404(task_id)

    if form.validate_on_submit():
        # add comment
        if anonymous is not None and anonymous.lower() in ['anonymous', 'a']:
            comment = Comment(comment=form.content.data, author_id=1, task_id=task_id)
        else:
            comment = Comment(comment=form.content.data, author_id=current_user.id, task_id=task_id)
        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('tasks.task', task_id=task_id))
    return render_template('comment_content.html', title='Add Comment',
                            form=form, task=task)


@tasks.route('/comment/<int:comment_id>/upload', methods=['GET', 'POST'])
@login_required
def add_comment_upload(comment_id):
    form = UploadForm()
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        abort(403)

    if request.method == 'POST' and 'File' in request.form and form.validate():
        filename = add_file(form.upload.data, secure_filename(comment.task.name))
        db.session.add(Material(filename=filename, orignial_name=form.upload.data.filename, upload_id=comment.id))
        db.session.commit()
        return redirect(url_for('tasks.add_comment_upload', comment_id=comment_id))
    elif request.method == 'POST' and 'Photo' in request.form:
        if 'image' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['image']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        filename = add_file(file, secure_filename(comment.task.name))
        db.session.add(Material(filename=filename, orignial_name=file.filename, upload_id=comment.id))
        db.session.commit()
        return redirect(url_for('tasks.add_comment_upload', comment_id=comment_id))

    return render_template('comment_upload.html', title='Add Upload',
                            form=form, comment=comment)


@tasks.route('/comment/<int:comment_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        abort(403)
    for material in comment.material:
        db.session.delete(material)
    db.session.commit()
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted!', 'success')
    return redirect(url_for('tasks.task', task_id=comment.task_id))


@tasks.route('/upload/<int:upload_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_upload(upload_id):
    material = Material.query.get_or_404(upload_id)
    delete_file(material.filename, 'static/material', 'material')
    db.session.delete(material)
    db.session.commit()
    next_page = request.args.get('origin')
    if next_page:
        return redirect(next_page)
    return redirect(url_for('tasks.schedule'))


@tasks.route('/add_task', methods=['GET', 'POST'])
@login_required
def add_task():
    form = AddTaskForm()
    form.subject.choices = [(subject.id, subject.name) for subject in Subject.query.all()]

    if form.validate_on_submit():
        db.session.add(Task(name=form.title.data,
                            description=form.description.data,
                            deadline=datetime.combine(form.deadline_date.data,
                            form.deadline_time.data),
                            user_id=current_user.id,
                            subject_id=form.subject.data))
        db.session.commit()
        flash('Task has been added.', 'success')
        return redirect(url_for('tasks.schedule'))
    return render_template('add_task.html', title='Add Task', form=form)


@tasks.route('/task/<int:task_id>/update', methods=['GET', 'POST'])
@login_required
def update_task(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user.id != task.user_id and current_user.status == 'user':
        abort(403)

    form = AddTaskForm()
    form.subject.choices = [(subject.id, subject.name) for subject in Subject.query.all()]

    if form.validate_on_submit():
        task.name = form.title.data
        task.description = form.description.data
        task.deadline = datetime.combine(form.deadline_date.data, form.deadline_time.data)
        task.subject_id = form.subject.data
        db.session.commit()
        flash('Task has been added.', 'success')
        return redirect(url_for('tasks.schedule'))

    if request.method == 'GET':
        form.title.data = task.name
        form.description.data = task.description
        form.deadline_date.data = task.deadline
        form.deadline_time.data = task.deadline
        form.subject.data = task.subject_id

    return render_template('add_task.html', title='Add Task', form=form)


@tasks.route('/task/<int:task_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user.status == 'user':
        abort(403)
    for comment in task.comment:
        db.session.delete(comment)
        for material in comment.material:
            db.session.delete(material)
            delete_file(material.filename, 'static/material', 'material')
        db.session.commit()
    db.session.commit()
    db.session.delete(task)
    db.session.commit()
    flash('Your task and all associated comments have been deleted!', 'success')
    return redirect(url_for('tasks.schedule'))


@tasks.route('/uploads/<string:filename>')
@login_required
def uploaded_file(filename):
    try:
        return send_from_directory(os.path.join(current_app.root_path, 'static/material'), filename=filename, as_attachment=False)
    except FileNotFoundError:
        abort(404)

webapp/users/routes.py
from webapp import bcrypt, db
from webapp.models import User
from webapp.users.forms import LoginForm, RegistrationForm, UpdateProfileForm
from webapp.users.utils import update_picture
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('tasks.schedule'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('tasks.schedule'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            return redirect(url_for('tasks.schedule'))
        flash('Login Unsuccessful. Please check email and password!', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/profile/<string:username>', methods=['GET', 'POST'])
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    image_file = url_for('static', filename='profile_pictures/' + user.image_file)
    if user == current_user:
        form = UpdateProfileForm()
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = update_picture(form.picture.data)
                current_user.image_file = picture_file
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash('Your Profile has been updated!', 'success')
            return redirect(url_for('users.profile', username=form.username.data))
        elif request.method == 'GET':
            form.username.data = current_user.username
            form.email.data = current_user.email
        return render_template('profile.html', title=user.username, user=user, image_file=image_file, form=form)
    return render_template('profile.html', title=user.username, user=user, image_file=image_file)

webapp/templates/_render_field.html
{% macro render_string_field(field, label=true) %}
  <div class="form-group">
    {% if label is true %}
      {{ field.label(class="form-control-label") }}
    {% endif %}
    {% if field.errors %}
      {{ field(class="form-control form-control-lg is-invalid", **kwargs)|safe }}
      <div class="invalid-feedback">
        {% for error in field.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% else %}
      {{ field(class="form-control form-control-lg", **kwargs)|safe }}
    {% endif %}
  </div>
{% endmacro %}

{% macro render_upload_field(field, label=true) %}
  {% if label is true %}
    {{ field.label(class="form-control-label") }}
  {% endif %}
  {{ field(class="form-control-file", **kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
      <span class="text-danger">{{ error }}</span><br>
    {% endfor %}
  {% endif %}
{% endmacro %}

webapp/templates/add_subject.html
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('main.config') }}">&lt Config</a>
{% endblock navbar %}
{% block body %}
  <div class="content-section">
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add Comment</legend>
      <form action="" method="POST">
        <input type="text" name="name" placeholder="subject" class="form-control form-control-lg"><br>
        <div class="form-group">
          <input type="submit" value="Add" class="btn btn-outline-info float-right">
        </div>
      </form><br>
    </fieldset>
  </div>
  <section id="subjects">
    {% for subject in subjects %}
      <div class="border-round spaced mt">
        {{ subject.id }} &emsp; {{ subject.name }}
      </div>
    {% endfor %}
  </section>
{% endblock body %}

webapp/templates/add_task.html
{% from "_render_field.html" import render_string_field %}
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('tasks.schedule') }}">&lt Schedule</a>
{% endblock navbar %}
{% block body %}

<section id=add_new_task>
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
    <fieldset>
      {{ render_string_field(form.title) }}
      {{ render_string_field(form.description) }}
      <div class="form-group">
        {{ form.deadline_date.label() }}<br>
        {{ form.deadline_date }}
        {{ form.deadline_time }}
      </div>
      <div class="form-group">
        {{ form.subject.label() }}<br>
        {{ form.subject }}
      </div>
      </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</section>

{% endblock body %}

webapp/templates/base.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

    {% block head %}{% endblock head %}

    {% if title %}
      <title>{{title}}</title>
    {% else %}
      <title>Selbsthilfegruppe 2.0</title>
    {% endif %}

  </head>
  <body>

    <section>
    <div class="navigation-bar">
      {% block navbar %}{% endblock navbar %}
      {% if current_user.is_authenticated %}
        <a class="float-right" href="{{url_for('users.logout')}}">logout</a>
        <a class="float-right" href="{{url_for('users.profile', username=current_user.username)}}">
          Profile
          <span class="text-muted"><small>({{current_user.username}})</small></span>
        </a>
      {% else %}
        <a class="float-right" href="{{url_for('users.login')}}">login</a>
        <a class="float-right" href="{{url_for('users.register')}}">register</a>
      {% endif %}
    </div>
  </section>

    <div class="wrap navbar-space">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block body %}{% endblock body %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/comment.html
{% from "_render_field.html" import render_string_field %}
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('tasks.task', task_id=task.id) }}">&lt {{ task.name }}</a>
{% endblock navbar %}
{% block body %}
  <div class="border-round bg-black spaced">
    <div class="bb-grey mb-4 pb-25">
      <a href="{{ url_for('users.profile', username=comment.author.username) }}">
        <img class="rounded-circle img-tiny" src="{{ url_for('static', filename='profile_pictures/' + comment.author.image_file) }}" alt="profile picture">
        {{ comment.author.username }}
      </a>
      <span class="text-muted">
        <small>{{ comment.time_updated.strftime('%H:%M %d.%m.%Y') }}</small>
      </span>
      {% if comment.author == current_user %}
        <span class="float-right">
          <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('tasks.add_comment_upload', comment_id=comment.id) }}">Manage Uploads</a>
          <div><a class="btn btn-danger btn-sm m-1 float-right" href="{{ url_for('tasks.delete_comment', comment_id=comment.id) }}">Delete</a></div>
        </span>
      {% endif %}
    </div>
    {% if comment.author == current_user %}
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.csrf_token() }}
        {{ render_string_field(form.content, label=false) }}
        {% for material in comment.material %}
          <div>
            <a href="{{ url_for('tasks.uploaded_file', filename=material.filename) }}">{{ material.orignial_name }}</a>
          </div>
        {% endfor %}
        <br>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info inline") }}
        </div>
      </form>
    {% else %}
      <p>{{comment.comment}}</p>
      {% for material in comment.material %}
        <div>
          <a href="{{ url_for('tasks.uploaded_file', filename=material.filename) }}">{{ material.orignial_name }}</a>
        </div>
      {% endfor %}
    {% endif %}
  </div>
{% endblock body %}

webapp/templates/comment_upload.html
{% from "_render_field.html" import render_upload_field %}
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('tasks.comment', comment_id=comment.id) }}">&lt Back to upload</a>
{% endblock navbar %}
{% block body %}
  <div class="content-section">
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add Uploads</legend>
      <h2>Browse File</h2>
      <form method="POST" enctype=multipart/form-data>
        {{ form.hidden_tag() }}
        {{ form.csrf_token() }}
        {{ render_upload_field(form.upload, label=false, class="inline") }}
        <input type="submit" name="File" class="btn btn-outline-info inline float-right">
      </form>
      <br>
      <h2>Take Photo</h2>
      <form method="POST" enctype=multipart/form-data>
        <input type="file" name="image" accept="image/*" capture="camera">
        <input type="submit" name="Photo" class="btn btn-outline-info inline float-right">
      </form>
      <br><br>
      <h2>Added Files</h2>
      <section id="cached files">
        {% for upload in comment.material %}
          <div class="border-round spaced mt">
            {{ upload.orignial_name }}
            <span class="float-right">
              <a href="{{ url_for('tasks.delete_upload', upload_id=upload.id, origin=url_for('tasks.add_comment_upload', comment_id=comment.id)) }}">x</a>
            </span>
            <br>
          </div>
        {% endfor %}
      </section>
    </fieldset>
  </div>
  <script>
    var input = document.querySelector('input[type=file]');
    input.onchange = function () {
      var file = input.files[0];
      upload(file);
    };

    function upload(file) {
      var form = new FormData(),
          xhr = new XMLHttpRequest();

      form.append('image', file);
      xhr.open('post', 'server.php', true);
      xhr.send(form);
    }
  </script>
  <!-- source: http://www.w3.org/TR/html-media-capture/ -->
{% endblock body %}

webapp/templates/config.html
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('users.profile', username=current_user.username) }}">&lt Profile</a>
{% endblock navbar %}
{% block body %}

  <section id="configurations">
    <h1>Configurations</h1>
    <a href="{{ url_for('main.add_subject')}} ">Add a Subject</a><br>
    <a href="{{ url_for('tasks.add_task')}} ">Add a Task</a><br>
  </section><br>

  <section id="editors">
    <h1>Editors</h1>
    {% for editor in editors %}
      <div>
        <a href="{{ url_for('users.profile', username=editor.username)}} ">{{ editor.username }}</a>
      </div>
    {% endfor %}
  </section>

  <section id="users">
    {% if current_user.status == 'god_mode' %}
      <h1>Users</h1>
      {% for user in users %}
        <span>
          <a href="{{ url_for('users.profile', username=user.username)}} ">{{ user.username }}</a> &emsp;
        </span>
      {% endfor %}
    {% endif %}
  </section>

{% endblock body %}

webapp/templates/login.html
{% from "_render_field.html" import render_string_field %}
{% extends "base.html" %}
{% block body %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Login</legend>
        {{ render_string_field(form.email) }}
        {{ render_string_field(form.password) }}
        <span class="form-group ml">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </span>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
      <!-- <div>
        <small class="text-muted ml-2">
          <a href="#">Forgot Password?</a>
        </small>
      </div> -->
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
  </div>
{% endblock body %}

webapp/templates/profile.html
{% from "_render_field.html" import render_string_field, render_upload_field %}
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('tasks.schedule') }}">&lt Schedule</a>
{% endblock navbar %}
{% block body %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}" alt="profile picture">
      <div class="media-body">
        <h1 class="inline">{{user.username}}</h1><br>
        email: <em>{{ user.email }}</em><br>
        {% if current_user.username == user.username and current_user.status != 'user' %}
            status: <a href="{{ url_for('main.config') }}">{{user.status}}</a>
        {% else %}
          {% if user.status == 'god_mode' %}
            status: editor
          {% else %}
            status: {{ user.status }}
          {% endif %}
        {% endif %}
      </div>
    </div>
    {% if form %}
      <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ render_string_field(form.username) }}
            {{ render_string_field(form.email) }}
            {{ render_upload_field(form.picture) }}
          </fieldset>
          <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
      </div>
    {% endif %}
  </div>
{% endblock body %}

webapp/templates/schedule.html
{% extends "base.html" %}
{% block body %}

<section id=add_new_task>
  <h1 class="inline">Tasks |<a href="{{ url_for('tasks.add_task') }}" class="button">+</a></h1>
</section>

<section id=table_of_tasks>
  <div class="mt-2 spaced">
    {% for task in schedule|sort(attribute='deadline') %}
      {% if not already_past(task.deadline) %}
        <div class="mt-1 mb-1">
          <a href="{{ url_for('tasks.task', task_id=task.id) }}">
            {{ task.name }}
            <span class="float-right">
               <small class="text-muted">{{ task.deadline.strftime('%d.%m.%Y %H:%M') }}</small>
            </span>
          </a>
        </div>
      {% endif %}
    {% endfor %}
  </div>
  <hr class="grey">
  <h5>Past Tasks</h5>
  <div class="mt-2 spaced">
    {% for task in schedule|sort(attribute='deadline')|reverse %}
      {% if already_past(task.deadline) %}
        <div class="mt-1 mb-1">
          <a href="{{ url_for('tasks.task', task_id=task.id) }}" class="text-muted">
            {{ task.name }}
            <span class="float-right">
               <small class="text-muted">{{ task.deadline.strftime('%d.%m.%Y %H:%M') }}</small>
            </span>
          </a>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</section>

{% endblock body %}

webapp/templates/task.html
{% extends "base.html" %}
{% block navbar %}
  <a href="{{ url_for('tasks.schedule') }}">&lt Schedule</a>
{% endblock navbar %}
{% block body %}

  <section id=title>
    <h1 class="inline">{{ task.name }}</h1>
    <span class="text-muted">{{ subject.name }}</span><br><br>
    {{ task.description }}<br>
    <p>deadline: {{ task.deadline.strftime('%d.%m.%Y %H:%M') }}</p>
  </section>

  <section id=comment>
    <h2 class="inline">Comments |
      <a href="{{ url_for('tasks.add_comment_content', task_id=task.id) }}" class=button>+</a>
    </h2>
    {% for comment in task.comment|reverse %}
      <div class="border-round bg-black mt-2 spaced">
        <div class="bb-grey mb-4">
          <a href="{{ url_for('users.profile', username=comment.author.username) }}">
            <img class="rounded-circle img-tiny" src="{{ url_for('static', filename='profile_pictures/' + comment.author.image_file) }}" alt="profile picture">
            {{ comment.author.username }}
          </a>
          <span class="text-muted">
            <small>{{ comment.time_updated.strftime('%H:%M %d.%m.%Y') }}</small>
          </span>
          <a href="{{ url_for('tasks.comment', comment_id=comment.id) }}" class="btn btn-secondary btn-sm m-1 float-right">View</a>
        </div>
        <p>{{ comment.comment }}</p>
        {% for material in comment.material %}
          <div>
            <a href="{{ url_for('tasks.uploaded_file', filename=material.filename) }}">{{ material.orignial_name }}</a>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </section>
{% endblock body %}